// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx3YxlMOGR_loxi2XCZmm-Fm2bNRKVkfg',
    appId: '1:412316429551:web:59a6aafa41fa220565bf1a',
    messagingSenderId: '412316429551',
    projectId: 'addclass-52114',
    authDomain: 'addclass-52114.firebaseapp.com',
    storageBucket: 'addclass-52114.appspot.com',
    measurementId: 'G-E1RRBR4ZP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGcnNuUTfAxUVyxWqZlq9v57e9VOZ8E8',
    appId: '1:412316429551:android:416cdfc2fb2b08eb65bf1a',
    messagingSenderId: '412316429551',
    projectId: 'addclass-52114',
    storageBucket: 'addclass-52114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTlJ8UKpvm_5EC8b8QW0sltfHh9fsNwY',
    appId: '1:412316429551:ios:6cad6f0a4f78ffc265bf1a',
    messagingSenderId: '412316429551',
    projectId: 'addclass-52114',
    storageBucket: 'addclass-52114.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTlJ8UKpvm_5EC8b8QW0sltfHh9fsNwY',
    appId: '1:412316429551:ios:6cad6f0a4f78ffc265bf1a',
    messagingSenderId: '412316429551',
    projectId: 'addclass-52114',
    storageBucket: 'addclass-52114.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx3YxlMOGR_loxi2XCZmm-Fm2bNRKVkfg',
    appId: '1:412316429551:web:4d5f0bd7e0e2aab065bf1a',
    messagingSenderId: '412316429551',
    projectId: 'addclass-52114',
    authDomain: 'addclass-52114.firebaseapp.com',
    storageBucket: 'addclass-52114.appspot.com',
    measurementId: 'G-VJ5TK0XZSE',
  );
}
